/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserReviewsRouteImport } from './routes/user-reviews'
import { Route as ExpertReviewsRouteImport } from './routes/expert-reviews'
import { Route as AppInOntwikkelingRouteImport } from './routes/app-in-ontwikkeling'
import { Route as IndexRouteImport } from './routes/index'

const UserReviewsRoute = UserReviewsRouteImport.update({
  id: '/user-reviews',
  path: '/user-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertReviewsRoute = ExpertReviewsRouteImport.update({
  id: '/expert-reviews',
  path: '/expert-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInOntwikkelingRoute = AppInOntwikkelingRouteImport.update({
  id: '/app-in-ontwikkeling',
  path: '/app-in-ontwikkeling',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-in-ontwikkeling': typeof AppInOntwikkelingRoute
  '/expert-reviews': typeof ExpertReviewsRoute
  '/user-reviews': typeof UserReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-in-ontwikkeling': typeof AppInOntwikkelingRoute
  '/expert-reviews': typeof ExpertReviewsRoute
  '/user-reviews': typeof UserReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-in-ontwikkeling': typeof AppInOntwikkelingRoute
  '/expert-reviews': typeof ExpertReviewsRoute
  '/user-reviews': typeof UserReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app-in-ontwikkeling' | '/expert-reviews' | '/user-reviews'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app-in-ontwikkeling' | '/expert-reviews' | '/user-reviews'
  id:
    | '__root__'
    | '/'
    | '/app-in-ontwikkeling'
    | '/expert-reviews'
    | '/user-reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppInOntwikkelingRoute: typeof AppInOntwikkelingRoute
  ExpertReviewsRoute: typeof ExpertReviewsRoute
  UserReviewsRoute: typeof UserReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-reviews': {
      id: '/user-reviews'
      path: '/user-reviews'
      fullPath: '/user-reviews'
      preLoaderRoute: typeof UserReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert-reviews': {
      id: '/expert-reviews'
      path: '/expert-reviews'
      fullPath: '/expert-reviews'
      preLoaderRoute: typeof ExpertReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-in-ontwikkeling': {
      id: '/app-in-ontwikkeling'
      path: '/app-in-ontwikkeling'
      fullPath: '/app-in-ontwikkeling'
      preLoaderRoute: typeof AppInOntwikkelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppInOntwikkelingRoute: AppInOntwikkelingRoute,
  ExpertReviewsRoute: ExpertReviewsRoute,
  UserReviewsRoute: UserReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
